name: dart_bitcoin_pushdata
description: Package where you can encode and decode the value as Bitcoin OP_PUSHDATA integer.
version: 1.0.3
homepage: https://github.com/dart-bitcoin-lib/dart-bitcoin-pushdata
repository: https://github.com/dart-bitcoin-lib/dart-bitcoin-pushdata

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  dart_bitcoin_ops: ^1.0.0

dev_dependencies:
  convert: ^3.0.1
  lints: ^1.0.0
  test: ^1.16.0